### ISSUE TITLE
Support for custom project structures & flexibility

### ISSUE THREAD

**Issue by Smaug6739** [Sheweny/framework#90]
# Support customs projects structures

The framework should support custom structures for projects like "module structures" and it should be more flexible.

## TODO

- [x] Refactor Loader (#88)
- [x] Check instance of structures
- [x] Don't save structures in `client.collections` automatically
- [x] Allow multiple clients
  - [x] Commands : Add strategies to register interactions

**Comment by Smaug6739** [comment]
Implemented in version 4.0.0-dev.11
