### ISSUE TITLE
Sheweny 5.0.0 roadmap

### ISSUE THREAD

**Issue by Smaug6739** [Sheweny/framework#97]
# Sheweny project, version 5.0.0 Roadmap

**This issue tracks changes and describes the roadmap of Sheweny V5.0.**

## New packages

- [ ] Heweny (Sheweny framework for a full object approach of discord.js) https://github.com/Sheweny/Heweny
- [ ] discord-resolve https://github.com/Sheweny/discord-resolve
- [ ] mistial [Sheweny/mistial](https://github.com/Sheweny/mistial)
- [ ] snippets [Sheweny/snippets](https://github.com/Sheweny/snippets)
- [ ] discord-markdown
- [ ] discord-utils

## New systems & versions & improvements

- [ ] Improve cooldown system #89 
- [ ] Support new permissions system :tada:
- [ ] Extension of structures (commands) #84 
- [ ] Improve CLI (no installation, more faster and lite)
- [ ] Improve errors handling (& fix errors in production)
- [ ] Create sharding system (See discord.js guide [Sharding guide](https://discordjs.guide/sharding/))
- [ ] With mistial, save cooldowns & config & structures into db

## Typescript

- [ ] Support Typescript 5.0
- [ ] Support decorators
- [ ] Improve types with V14 structures

## Other changes

- [ ] Convert repos & separated packages into monorepo
- [ ] Fix documentation search
- [ ] Support ESM #88 #91
